"""init

Revision ID: 883992f5b42f
Revises:
Create Date: 2025-10-24 14:38:23.383584

"""

from typing import Sequence, Union

import sqlalchemy as sa
import sqlalchemy_utils
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '883992f5b42f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.run_ddl_script('2025_10_24_1438_ext-hstore_883992f5b42f.sql')
    op.run_ddl_script('2025_10_24_1438_ext-pg_trgm_883992f5b42f.sql')
    op.run_ddl_script('2025_10_24_1438_ext-unaccent_883992f5b42f.sql')
    op.run_ddl_script('2025_10_24_1438_ext-uuid-ossp_883992f5b42f.sql')
    op.run_ddl_script('2025_10_24_1438_ext-btree_gin_883992f5b42f.sql')
    op.run_ddl_script('2025_10_24_1438_ext-btree_gist_883992f5b42f.sql')
    op.run_ddl_script('2025_10_24_1438_ext-fuzzystrmatch_883992f5b42f.sql')
    op.run_ddl_script('2025_10_24_1438_tgr_func-update_updated_at_column_883992f5b42f.sql')

    op.create_table(
        'users',
        sa.Column('id', sa.Uuid(), server_default=sa.text('uuid_generate_v4()'), nullable=False),
        sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('deleted_at', postgresql.TIMESTAMP(timezone=True), nullable=True),
        sa.Column('username', sa.String(length=255), nullable=False),
        sa.Column('password', sa.String(length=255), nullable=True),
        sa.Column('cellphone', sa.String(length=45), nullable=False),
        sa.Column(
            'state',
            postgresql.ENUM('disabled', 'enabled', name='user_state_type'),
            server_default='enabled',
            nullable=False,
        ),
        sa.Column('nickname', sa.String(length=255, collation='zh-x-icu'), nullable=False),
        sa.Column('gender', postgresql.ENUM('male', 'female', 'unknown', name='gender_type'), nullable=False),
        sa.Column('avatar', sa.String(), nullable=False),
        sa.Column('is_admin', sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('cellphone'),
        sa.UniqueConstraint('id'),
        sa.UniqueConstraint('username'),
    )

    op.run_ddl_script('2025_10_24_1438_tgr-update_updated_at_column_users_883992f5b42f.sql')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP TRIGGER IF EXISTS tgr_update_updated_at_column ON users;')

    op.drop_table('users')

    op.execute('DROP FUNCTION IF EXISTS update_updated_at_column;')

    postgresql.ENUM(name='user_state_type').drop(op.get_bind())
    postgresql.ENUM(name='gender_type').drop(op.get_bind())

    op.execute('DROP EXTENSION IF EXISTS fuzzystrmatch;')
    op.execute('DROP EXTENSION IF EXISTS btree_gin;')
    op.execute('DROP EXTENSION IF EXISTS btree_gist;')
    op.execute('DROP EXTENSION IF EXISTS "uuid-ossp";')
    op.execute('DROP EXTENSION IF EXISTS unaccent;')
    op.execute('DROP EXTENSION IF EXISTS pg_trgm;')
    op.execute('DROP EXTENSION IF EXISTS hstore;')
    # ### end Alembic commands ###
